config/routes.rb
Rails.application.routes.draw do

  root "listings#index"

  get '/listings/new', to: "listings#new"
  post '/listings/new', to: "listings#create"
  resources :listings, except: [:new, :create], shallow: true do
    resources :comments
    resources :reservations, only: [:new, :create, :index]
  end
  
  resources :users, only: [:new, :create] 
  get '/login', to: "sessions#new", as: "login"
  post '/login', to: "sessions#create"
  delete "logout", to: "sessions#destroy", as: "logout"
  get "logout", to: "listings#index"
  
    get 'auth/:provider/callback', to: 'sessions#create'
    get 'signout', to: 'sessions#destroy', as: 'signout'
    

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :listing
end

app/models/listing.rb
class Listing < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	has_many :reservations

	validates :room_type, presence: true
	validates :home_type, presence: true
	validates :accomodates, presence: true
	validates :city, presence: true
	validates :bedroom, presence: true
	validates :bathroom, presence: true
	validates :bedcount, presence: true
	validates :listing_name, presence: true
	validates :summary, presence: true

	mount_uploaders :images, ImageForListingUploader
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :user
	belongs_to :listing
	validates :checkin_date, presence: true
	validates :checkout_date, presence: true
	validates :person, presence: true
	validates :checkin_date, :checkout_date, :overlap => {:scope => "listing_id"}

	# scope :overlapping, -> (reservation) {
 #    select("(DATEDIFF('day', checkin_date, ?) * DATEDIFF('day', ?, checkout_date)) >= 0", reservation.checkout_date, reservation.checkin_date)
 #  }

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :reservations
	has_many :commments
	has_many :listings
	has_secure_password
	mount_uploader :avatar, AvatarUploader
	# validates :username, presence: true, uniqueness: true
	# validates :gender, presence: true
	# validates :birthday, presence: true
	# validates :email, presence: true, uniqueness: true
	# validates :contact, presence: true
	# validates :address, presence: true
	# validates :about_you, presence: true
	# validates :password, presence: true
	def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.provider = auth.provider 
    user.uid      = auth.uid
    user.username = auth.extra.raw_info.name
    user.email   	= auth.extra.raw_info.email
    user.password = "12345678"
    user.birthday = auth.extra.raw_info.birthday
    user.gender 	= auth.extra.raw_info.gender
    user.remote_avatar_url   = auth.info.image.gsub('http://','https://')
    byebug
    user.save!
  end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  def authenticate_user!
  	if user_logged_in?
  	else
  		redirect_to login_path
  		flash[:warning] = "please login"
  	end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

def new
	@listing = current_listing
end

private


end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
before_action :set_listing, only: [:edit, :update, :destroy]
before_action :authenticate_user!, except: [:index]
before_action :check_correct_user, only: [:edit, :update, :destroy]

def index
@listing = Listing.all
end

def new
end

def create
  @listing = current_user.listings.new(listing_params)
  if @listing.save!
  	redirect_to listings_path
  	flash[:notice] = "Listing successfully created!"
  else
  	render :new
  	flash[:warning] = "Listing not created!"
  end
end

def show
	set_listing
end

def edit
	set_listing
end

def update
	if set_listing.update(listing_params)
	redirect_to @listing
else
	render :edit
end
end

def destroy
	@listing.destroy
	redirect_to listings_path
end


private
    def listing_params
      params.require(:listing).permit(:home_type, :room_type, :accomodates, :city, :bedroom, :bathroom, :bedcount, :listing_name, :summary, :price, images: [])
    end

    def set_listing
      @listing = Listing.find(params[:id])
    end

    def check_correct_user
    	unless @listing.user == current_user
    		flash[:warning] = "Unauthorized"
    		redirect_to listing_path
    	end

    end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

def new
	@listing = current_listing
	@reservation = @listing.reservations.new
end

def create

	@reservation = current_listing.reservations.new(reservation_params.merge(user: current_user))
	if @reservation.save
		a = @reservation.checkout_date- @reservation.checkin_date
		@reservation[:daycount] = a.to_i
		@reservation[:totalprice] = (a.to_i)*(current_listing.price)
		@reservation.save
		ReservationWorker.perform_async(@reservation.id)
		# ReservationMailer.booking_email(@reservation).deliver_now
		flash[:success] = "reservation done!"
		redirect_to root_path
	else
		# render ":reservations#new"
		flash[:warning] = "reservation cannot be done!"
		@listing = @reservation.listing
		render :new
	end

	def index
		@reservation = Reservation.all
	end
end

private
    def reservation_params
      params.require(:reservation).permit(:checkin_date, :checkout_date, :person, :listing_id, :user_id, :totalprice, :daycount)
    end

    def overlap

    end


end 

app/controllers/sessions_controller.rb
class SessionsController <ApplicationController
 before_action :authenticate_user!, only: []

	def new
	end

	def create
		if !env["omniauth.auth"].nil?
			@user = User.from_omniauth(env["omniauth.auth"])
			session[:user_id] = @user.id
			redirect_to root_path
		else 
			if @user = User.find_by(email: params[:session][:email])
		  @user && @user.authenticate(params[:session][:password])
			session[:user_id] = @user.id
			redirect_to root_path
			else
			redirect_to login_path
			flash[:warning] = "Invalid Username or password"
	  end
	  end
	end

	def destroy
	  session[:user_id] = nil
	  redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def new 
	@user = User.new
end

def create
	@user = User.new(user_params)
		if @user.save
		flash[:notice] = "Account successfully created!"
		redirect_to login_path
	else
		render :new
		flash[:warning] = "Account not created!"
	end
end

private

def user_params
	params.require(:user).permit(:username, :email, :password, :contact, :address, :about_you, :birthday, :gender, :password_confirmation, :avatar)

end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

	def user_logged_in?
		current_user.present?
	end


	def current_listing
		Listing.find(params[:listing_id])
	end

end

app/views/comments/new.html.erb
<h1><%= @listing.listing_name %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PairBnb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="homebtn">
		<span class="btn btn-success">
<%= link_to "Home", root_path %>
		</span>
    <% if user_logged_in? %>
    <span class="btn btn-success">
      <%= link_to "logout", logout_path, method: :delete %>
    </span>
    <span class="btn btn-success">
      <%= "Welcome #{current_user.username}" %>
    </span>
    <% else %>
		<span class="btn btn-success">
<%= link_to "Signup", new_user_path %>
		</span>
    
    <%= link_to "/auth/facebook", id: "sign_in" do %>
      <span class="btn btn-success">
        "Sign in with Facebook",
      </span>

    <% end %>
		
    <span class="btn btn-success">
<%= link_to "Login", login_path %>
		</span>
    <% end %>
	</div>	

	  <div>
    <table>
      <% flash.each do |k| %>
        <tr>
          <td><%= k %></td>
        </tr>
      <% end %>
    </table>
  </div>
<%= yield %>

</body>
</html>

app/views/listings/edit.html.erb
<h1>Edit your listing</h1>

<%= form_for @listing, html: {multipart: true} do |t| %>
	<div class="test">
		<label class="col-sm-2">Room Type:</label>
		<%= t.text_field :room_type %>
	</div>

	<div class="test">
		<label class="col-sm-2">Home Type:</label>
		<%= t.text_field :home_type %>
	</div>

	<div class="test">
		<label class="col-sm-2">Accomodates:</label>
		<%= t.text_field :accomodates %>
	</div>

	<div class="test">
		<label class="col-sm-2">City:</label>
		<%= t.text_field :city %>
	</div>

	<div class="test">
		<label class="col-sm-2">Bedroom:</label>
		<%= t.text_field :bedroom %>
	</div>

	<div class="test">
		<label class="col-sm-2">Bathroom:</label>
		<%= t.text_field :bathroom %>
	</div>

	<div class="test">
		<label class="col-sm-2">Bedcount:</label>
		<%= t.text_field :bedcount %>
	</div>

		<div class="test">
		<label class="col-sm-2">Price:</label>
		<%= t.text_field :price %>
	</div>

	<div class="test">
		<label class="col-sm-2">Listing Name:</label>
		<%= t.text_field :listing_name %>
	</div>

	<div class="test">
		<label class="col-sm-2">Summary:</label>
		<%= t.text_area :summary %>
	</div>

	<div class="test">
		<label class="col-sm-2">Photo:</label>
		<%= t.file_field :image, multiple: true%>
	</div>
	<br>
	<div>
		<%= t.submit "Edit listing!" %>
	</div>



<% end %>

app/views/listings/index.html.erb
<h1>Welcome to PairBnb</h1>

<% @listing.each_with_index do | t, index| %>
<div>
<%= link_to t do %>
<%= "#{index+1}. #{t.listing_name}" %>
</div>
<% end %>

<% end %>
<br>
<div class="btn btn-warning">
<%= link_to "Post a new listings!", listings_new_path %>
</div>

app/views/listings/new.html.erb
<div class="class-title">
<h1>Create a new listing here!</h1>
</div>
	<%= form_for :listing, html: {multipart: true} do |t| %>
	<div class="test">
		<label class="col-sm-2">Room Type:</label>
		<%= t.text_field :room_type %>
	</div>

	<div class="test">
		<label class="col-sm-2">Home Type:</label>
		<%= t.text_field :home_type %>
	</div>

	<div class="test">
		<label class="col-sm-2">Accomodates:</label>
		<%= t.text_field :accomodates %>
	</div>

	<div class="test">
		<label class="col-sm-2">City:</label>
		<%= t.text_field :city %>
	</div>

	<div class="test">
		<label class="col-sm-2">Bedroom:</label>
		<%= t.text_field :bedroom %>
	</div>

	<div class="test">
		<label class="col-sm-2">Bathroom:</label>
		<%= t.text_field :bathroom %>
	</div>

	<div class="test">
		<label class="col-sm-2">Bedcount:</label>
		<%= t.text_field :bedcount %>
	</div>

		<div class="test">
		<label class="col-sm-2">Price:</label>
		<%= t.text_field :price %>
	</div>

	<div class="test">
		<label class="col-sm-2">Listing Name:</label>
		<%= t.text_field :listing_name %>
	</div>

	<div class="test">
		<label class="col-sm-2">Summary:</label>
		<%= t.text_area :summary %>
	</div>

	<div class="test">
		<label class="col-sm-2">Photo:</label>
		<%= t.file_field :images , multiple: true%>
	</div>
	<br>

	<div>
		<%= t.submit "Create Listing" %>
	</div>

<% end %>

app/views/listings/show.html.erb
<h1>Listing : <%= @listing.listing_name %></h2>

<h2>Price: <%= @listing.price %></h2>

<h2>About it: <%= @listing.summary %></h2>

<h2>Home type: <%= @listing.home_type %></h2>

<h2>Room type: <%= @listing.room_type %></h2>

<h2>City: <%= @listing.city %></h2>

<h2>Bathroom: <%= @listing.bathroom %></h2>

<h2>Bedcount: <%= @listing.bedcount %></h2>

<h2>Bedroom: <%= @listing.bedroom %></h2>

<h2>Accomodates: <%= @listing.accomodates %></h2>

<h2>Created: <%= @listing.created_at %></h2>

<h2>Updated: <%= @listing.updated_at %></h2>

<p>
<label><%= @listing.listing_name %></label>
		<% @listing.images.each do |image| %>
    	<%= image_tag image.url.to_s if image.url.present? %>
    <% end %>
</p>
<div class="btn btn-warning">
<%=	link_to "Delete this post", listing_path(@listing), method: :delete %></div>

<div class="btn btn-warning">
<%=	link_to "Edit this post", edit_listing_path %></div>

<div class="btn btn-warning">
<%= link_to "Back", root_path %>
</div>

<div class="btn btn-warning">
<%= link_to "Book this place", new_listing_reservation_path(@listing) %>
</div>

app/views/reservations/new.html.erb
	<% @reservation.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>

<h1> <%= @listing.listing_name %></h1>

		<% @reservation.errors.full_messages.each do |msg| %>
      <p><%= msg %></p>
    <% end %>

		<% @listing.images.each do |image| %>
    	<%= image_tag image.url.to_s if image.url.present? %>
    <% end %>

 <p>Price per night:  RM<%= @listing.price %></p>

 <%= form_for [@listing, @reservation] do |t| %>
		<div class="test">
		<label class="col-sm-2">Check-in date:</label>
		<%= t.date_field :checkin_date %>
	</div>

		<div class="test">
		<label class="col-sm-2">Check-out date:</label>
		<%= t.date_field :checkout_date %>
	</div>

		<div class="test">
		<label class="col-sm-2">Person:</label>
		<%= t.text_field :person %>
	</div>

<br>
<div>
		<%= t.submit "Book this date" %>
</div>

	<% end %>

app/views/users/new.html.erb
<h1>Create an account here!</h1>

<%= form_for @user, html: {multipart: true} do |t| %>
	<div class="test">
		<label class="col-sm-2">Username:</label>
		<%= t.text_field :username %>
	</div>

		<div class="test">
		<label class="col-sm-2">Email:</label>
		<%= t.email_field :email %>
	</div>

		<div class="test">
		<label class="col-sm-2">Password:</label>
		<%= t.password_field :password %>
	</div>

		<div class="test">
		<label class="col-sm-2">Confirmation password:</label>
		<%= t.password_field :password_confirmation %>
	</div>

		<div class="test">
		<label class="col-sm-2">Birthday:</label>
		<%= t.text_field :birthday %>
	</div>

		<div class="test">
		<label class="col-sm-2">Contact:</label>
		<%= t.text_field :contact %>
	</div>

		<div class="test">
		<label class="col-sm-2">Address:</label>
		<%= t.text_field :address %>
	</div>

		<div class="test">
		<label class="col-sm-2">Gender:</label>
		<%= t.text_field :gender %>
	</div>

		<div class="test">
		<label class="col-sm-2">About you:</label>
		<%= t.text_area :about_you %>
	</div>

		<div class="test">
		<label class="col-sm-2">Profile Pic:</label>
		<%= t.file_field :avatar%>
	</div>


	<br>

	<div>
		<%= t.submit "Create Account" %>
	</div>

<% end %>